# Generated by Django 5.0.7 on 2024-07-22 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroTecnicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto_responsavel', models.CharField(max_length=100)),
                ('tecnico_responsavel', models.CharField(max_length=100)),
                ('assunto', models.CharField(max_length=100)),
                ('info_atendimento', models.TextField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CadastroViabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto_responsavel', models.CharField(max_length=100)),
                ('comercial_responsavel', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('descricao_projeto', models.TextField()),
                ('descricao_comercial', models.TextField()),
                ('coluna_timestamp', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto_responsavel', models.CharField(max_length=100)),
                ('tecnico_responsavel', models.CharField(max_length=100)),
                ('info_atendimento', models.TextField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipamentoEmTeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('equipamento', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('problema', models.CharField(max_length=200)),
                ('mac', models.CharField(max_length=17, unique=True)),
                ('status', models.CharField(choices=[('C', 'Cadastrado'), ('ET', 'Em Teste'), ('T', 'Testado'), ('RE', 'Retestado'), ('CP', 'Campo')], default='ET', max_length=2)),
                ('data_teste', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EquipamentoParaCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('equipamento', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('problema', models.CharField(max_length=200)),
                ('relato_teste', models.CharField(max_length=800)),
                ('mac', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('C', 'Cadastrado'), ('ET', 'Em Teste'), ('T', 'Testado'), ('RE', 'Retestado'), ('CP', 'Campo')], default='CP', max_length=2)),
                ('data_teste', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EquipamentoRegistrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('equipamento', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('problema', models.CharField(max_length=200)),
                ('mac', models.CharField(max_length=17, unique=True)),
                ('status', models.CharField(choices=[('C', 'Cadastrado'), ('ET', 'Em Teste'), ('T', 'Testado'), ('RE', 'Retestado'), ('CP', 'Campo')], default='C', max_length=2)),
                ('data_teste', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EquipamentoRetestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('equipamento', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('problema', models.CharField(max_length=200)),
                ('relato_teste', models.CharField(max_length=800)),
                ('mac', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('C', 'Cadastrado'), ('ET', 'Em Teste'), ('T', 'Testado'), ('RE', 'Retestado'), ('CP', 'Campo')], default='T', max_length=2)),
                ('data_teste', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EquipamentoReteste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('equipamento', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('problema', models.CharField(max_length=200)),
                ('relato_teste', models.CharField(max_length=800)),
                ('mac', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('C', 'Cadastrado'), ('ET', 'Em Teste'), ('T', 'Testado'), ('RE', 'Retestado'), ('CP', 'Campo')], default='T', max_length=2)),
                ('data_teste', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EquipamentoTestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('equipamento', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('problema', models.CharField(max_length=200)),
                ('relato_teste', models.CharField(max_length=800)),
                ('mac', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('C', 'Cadastrado'), ('ET', 'Em Teste'), ('T', 'Testado'), ('RE', 'Retestado'), ('CP', 'Campo')], default='T', max_length=2)),
                ('data_teste', models.DateTimeField(auto_now_add=True)),
                ('campo', models.CharField(choices=[('S', 'Sim'), ('N', 'Nao')], max_length=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
